### ISSUE TITLE
possible to connect on leshan with secure connection ??

### ISSUE THREAD

**Issue by krunalchauhan637** [PelionIoT/pelion-client-lite#10]
By using pelion-client-lite, Is it possible to connect on leshan with secure connection ??
By just replacing leshan cradential in mbed_cloud_dev_credentials.c ??

What are dependencies require to up & run over leshan for secure connection ??

**Comment by teetak01** [comment]
Hi,

No, this library currently supports only pelion connectivity. Also the bootstrap flow as implemented is not fully complient with LwM2M in Client LITE library.

But instead https://github.com/PelionIoT/mbed-cloud-client library can be used also with Leshan, although the provisioning part is not documented for third-party clouds and requires direct use of the "mbed-client" functionality, bypassing the "mbed-cloud-client" in front of it, which implements Pelion-specific logic.
