### ISSUE TITLE
Failed to switch from bootstarp to register server in non-secure connection

### ISSUE THREAD

**Issue by krunalchauhan637** [PelionIoT/pelion-client-lite#9]
Setup:
Board: NUCLEO_F429ZI

[scenario1_bootstrap_register_with_log.txt](https://github.com/PelionIoT/pelion-client-lite/files/7386831/scenario1_bootstrap_register_with_log.txt))
First I done configuration on pelion client for NUCLEO_F429ZI. 
- create certificate on pelion
- download mbed_cloud_dev_credentials.c
- compile with above file. load binary 
- First it is bootstarp done & automatically redirect to register which is work fine

[scenario2.txt](https://github.com/PelionIoT/pelion-client-lite/files/7386857/scenario2.txt))
Using same pelion-client-lite, I want to perform bootstap & register on our leshan server
But in this case I am using non secure connection. 
In this case bootstarp is done but it is not redirect for registartion.

Que: Is this library test for non secure ??
Que: What dependency or changes required for non scure connection 
Que: Why it is not redirect for register flow

**Comment by teetak01** [comment]
Hi, Client LITE does not currently support such features, it only supports secure connections with Pelion. If you want to test with Leshan, I would recommend to use Pelion Device Management Client library instead.

https://github.com/PelionIoT/mbed-cloud-client

https://developer.pelion.com/docs/device-management/current/connecting/device-management-client-tutorials.html

**Comment by krunalchauhan637** [comment]
Thanks  @teetak01  for quick reply.

**Comment by teetak01** [comment]
I'll close this as this is not something we plan to change.

**Comment by krunalchauhan637** [comment]
By using pelion-client-lite,  Is it possible to connect on leshan with secure connection ??
By just replacing  leshan cradential in mbed_cloud_dev_credentials.c ??
